services:
  - type: web
    name: face-recognition-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn face-recognition-opencv.face_app_web:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18